apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic
  namespace: monitoring
spec:
  version: 8.3.3
  auth:
    roles:
    - secretName: elasticsearch-roles
  # secureSettings:
  # - secretName: elasticsearch-s3-creds
  http:
    tls:
      certificate:
        secretName: nginx-certificate
  nodeSets:
  - name: elastic
    count: 1
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        initContainers:
        - name: install-plugins
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin install --batch repository-s3
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: do-block-storage
