apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: monitoring
  namespace: default
spec:
  version: 8.3.3
  count: 1
  elasticsearchRef:
    name: elastic
  http:
    tls:
      certificate:
        secretName: nginx-certificate