apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: content
  namespace: content
spec:
  version: 7.10.1
  http:
    tls:
      selfSignedCertificate:
        subjectAltNames:
        - dns: content-es-http.content.svc.cluster.local
        - dns: localhost
  nodeSets:
  - name: content
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
        storageClassName: do-block-storage
