name: Build and Deploy

on:
  push:
    branches: master

jobs:
  configure-infrastructure:
    runs-on: ubuntu-latest
    name: Update infrastructure
    steps:
    - uses: actions/checkout@v2.3.4

    - name: 'Prepare Terraform'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.29
        tf_actions_subcommand: 'init'
        tf_actions_comment: false
        args: '-backend-config="token=${{ secrets.TF_API_TOKEN }}" -backend-config="organization=foreign-language-reader"'

    - name: 'Apply infrastucture changes'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.29
        tf_actions_subcommand: 'apply'
        tf_actions_comment: false