apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic
  namespace: default
spec:
  version: 7.10.1
  auth:
    roles:
    - secretName: elasticsearch-roles
  http:
    tls:
      selfSignedCertificate:
        subjectAltNames:
        - dns: elastic-es-http.default.svc.cluster.local
        - dns: localhost
    service:
      spec:
        type: LoadBalancer 
  nodeSets:
  - name: elastic
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
    podTemplate:
      spec:
        initContainers:
        - name: install-plugins
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin install --batch repository-s3
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: do-block-storage
