apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: default
spec:
  version: 7.10.1
  count: 1
  elasticsearchRef:
    name: elastic
  http:
    tls:
      certificate:
        secretName: nginx-certificate
    service:
      spec:
        type: LoadBalancer 